default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer
        verbose: true
      - id: check-yaml

  - repo: local
    hooks:
      - id: go-unit-test
        name: Run unit test
        language: system
        entry: make test
        pass_filenames: false
        types: [go]
        always_run: true
        verbose: true
        fail_fast: true
        stages: [pre-commit]
