networks:
  integration-test:

services:
  integration-test:
    build:
      context: .
      dockerfile: Dockerfile.it
    environment:
      - DB_CONNECTION_STRING=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - $PWD:/go/src
    networks:
      - integration-test

  db:
    image: postgres:16
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - integration-test

volumes:
  db-data:
