name: Continuous integration

on:
  push:
    branches:
      - main

jobs:
  unit-test:
      name: Unit Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.22.3
        - name: Run Unit Test
          run: make test-coverage

        - name: Upload coverage
          uses: actions/upload-artifact@v4
          with:
            name: coverage
            path: ./coverage.out

  integration-test:
      name: Integration Test
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Run Integration Test
          run: make integration-test

  build-and-push-docker-image:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: [unit-test, integration-test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3

      - name: Set up Git SHA
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.GIT_SHA }}
